#!/bin/bash
#################################################
##   LaTeX German Letter von Maximilian Ruta   ##
##   ist als Public Domain freigegeben.        ##
#################################################
for file in "Vorlage.acn" "Vorlage.acr" "Vorlage.alg" "Vorlage.aux" "Vorlage.bbl" "Vorlage.blg" "Vorlage.dvi" "Vorlage.glg" "Vorlage.glo" "Vorlage.gls" "Vorlage.ist" "Vorlage.lof" "Vorlage.log" "Vorlage.lot" "Vorlage.out" "Vorlage.synctex.gz" "Vorlage.toc" "Vorlage-pics.pdf" "Vorlage-pics.ps"; do
  if [ -f "${file}" ]; then
    rm "${file}"
  fi;
done;
